### ISSUE TITLE
coreui vs bootstrap-vue?

### ISSUE THREAD

**Issue by laoshaw** [coreui/bootstrap-vue#4]
so this project uses the same name as https://bootstrap-vue.org/?

what's different between coreui/bootstrap-vue vs coreui? the latter also claims to be a bootstrap5 UI kit.

then there is https://github.com/cdmoro/bootstrap-vue-3

**Comment by mrholek** [comment]
@laoshaw CoreUI for Vue has our own design system and more components like Sidebar, SmartTables, etc. @coreui/bootstrap-vue has Bootstrap styles and only Bootstrap components.

**Comment by laoshaw** [comment]
Thanks. Yes bootstrap5-vue3 is of high interest for many. I wonder how many BT5 components are built already in this project, e.g. how complete for the 1.0.0 release(hope it will be out soon)?

I did find two components led to 404:

https://coreui.io/bootstrap-vue/components/chart.html

https://coreui.io/bootstrap-vue/components/icon.html

**Comment by mrholek** [comment]
@laoshaw we have all Bootstrap 5 components, Charts, and Icon is not available in this library. The project is production-ready, but we have to update documentation, that's why it is Beta.

**Comment by laoshaw** [comment]
What options do I have for charts and icons if they are not available? e.g use something like https://github.com/J-T-McC/vue3-chartjs for chart, and import bootstrap5's icons directly?

Looking forward to 1.0.0.

**Comment by mrholek** [comment]
For charts, you can use this - https://coreui.io/vue/docs/4.1/components/chart.html
For icons, this - https://coreui.io/vue/docs/4.1/components/icon.html

**Comment by laoshaw** [comment]
Thanks!!
